# Generated by Django 3.2.7 on 2021-09-23 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('isComplete', models.BooleanField(default=False)),
                ('taskBegin', models.DateTimeField()),
                ('taskEnd', models.DateTimeField()),
                ('grade', models.FloatField(default=0.0)),
            ],
        ),
    ]
