# Generated by Django 3.2.7 on 2021-09-23 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sessitionTime', models.IntegerField(choices=[(25, '25 min'), (30, '30 min'), (45, '45 min')], default=25)),
                ('breakTime', models.IntegerField(choices=[(5, 'short break'), (15, 'long break')], default=5)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
