# Generated by Django 3.2.7 on 2021-09-23 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('file', 'file'), ('text', 'text'), ('url', 'url')], default='file', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/')),
                ('url', models.URLField(blank=True, null=True)),
                ('text', models.TextField(blank=True, max_length=300, null=True)),
                ('dateAdded', models.DateTimeField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='media_manager.category')),
            ],
        ),
    ]
